
services:
  - type: web
    name: webmipham
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn WEBMIPHAM.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: WEBMIPHAM.settings
      - key: PYTHON_VERSION
        value: 3.10
    autoDeploy: true